export const TEST_MEALS = [
  "Spaghetti Bolognese",
  "Chicken Curry",
  "Beef Stroganoff",
  "Vegetable Stir Fry",
  "Fish Tacos",
  "Lamb Kebabs",
  "Pasta Carbonara",
  "Chicken Alfredo",
  "Beef Tacos",
  "Vegetable Curry",
  "Chicken Fajitas",
  "Beef Burgers",
  "Vegetable Lasagna",
  "Fish and Chips",
  "Lamb Chops",
  "Pasta Primavera",
  "Chicken Parmesan",
  "Beef Stew",
  "Vegetable Soup",
  "Fish Pie",
  "Lamb Stew",
  "Pasta Bolognese",
  "Chicken Stir Fry",
  "Beef Chili",
  "Vegetable Pizza",
  "Chicken Salad",
  "Beef Salad",
  "Vegetable Salad",
  "Fish Salad",
  "Lamb Salad",
];

export const TEST_BOOKS = [
  { name: "The Joy of Cooking", author: "Irma S. Rombauer" },
  { name: "Mastering the Art of French Cooking", author: "Julia Child" },
  { name: "The Professional Chef", author: "The Culinary Institute of America" },
  { name: "Essentials of Classic Italian Cooking", author: "Marcella Hazan" },
  { name: "The Flavor Bible", author: "Karen Page and Andrew Dornenburg" },
];
