export const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL!;
export const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;
export const POWERSYNC_URL = process.env.EXPO_PUBLIC_POWERSYNC_URL!;

export const TEST_FREE_EMAIL = process.env.EXPO_PUBLIC_TEST_FREE_EMAIL!;
export const TEST_EMAIL = process.env.EXPO_PUBLIC_TEST_EMAIL!;

export const TEST_FREE_ID_PREFIX = "111";
export const TEST_ID_PREFIX = "222";

export const TEST_PASSWORD = process.env.EXPO_PUBLIC_TEST_PASSWORD!;

export const REVENUE_CAT_ANDROID_API_KEY = process.env.EXPO_PUBLIC_REVENUE_CAT_ANDROID_API_KEY!;

export const LOCAL_USER_ID = "00000000-0000-0000-0000-000000000000";
